[api]
# Enable rate limiting
enable_rate_limiting = true

# Max requests per IP per minute
rate_limit_requests = 100  

# Rate limit window in seconds
rate_limit_window = 60

# Enable JWT verification
verify_jwt = true
