[functions.price-updater]
verify_jwt = false
import_map = "./import_map.json"
[functions.price-updater.environment]
SUPABASE_URL = "{{SUPABASE_URL}}"
SUPABASE_SERVICE_ROLE_KEY = "{{SUPABASE_SERVICE_ROLE_KEY}}"
TRADERMADE_API_KEY = "{{TRADERMADE_API_KEY}}"

[functions.login-limit]
enabled = true
verify_jwt = true
import_map = "./functions/login-limit/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/login-limit/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/login-limit/*.html" ]
